title: Net4Email
author:
  name: desarrollo
  email: soporte@netquatro.com
taxonomies:
  - category
  - tag
  - mail
  - correo
  - venezuela
  - bolivares
metadata:
  description: 'correo masivo en venezuela pagado en bolivares, miles de correos para tu campaña'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: your-email@domain.com
description: 'Deseas enviar miles o millones de correos en campañas de correo pagando en bolivares, contrata net4email'
social:
  -
    label: Twitter
    url: 'https://twitter.com/netquatro'
    icon: twitter
  -
    label: Facebook
    url: 'https://www.facebook.com/netquatro/'
    icon: facebook
copyright:
  line1: Netquatro
  line2: 'Design:'
  url: 'http://www.netquatro.com'
  url_label: Netquatro
logo:
  text1: Netquatro
