title: Net4Cloud
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Twenty is a free and responsive theme for **Grav**. Its a port of Twenty template by HTML5 UP.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
social:
  -
    label: Twitter
    url: 'https://twitter.com/netquatro'
    icon: twitter
  -
    label: Facebook
    url: 'https://www.facebook.com/netquatro/'
    icon: facebook
copyright:
  line1: Netquatro
  line2: 'Design:'
  url: 'http://www.netquatro.com'
  url_label: 'Netquatro'
logo:
  text1: Netquatro
submenu:
  -
    text: 'Dolore Sed'
    link: '#'
  -
    text: Consequat
    link: '#'
  -
    text: 'Lorem Magna'
    link: '#'
  -
    text: 'Sed Magna'
    link: '#'
  -
    text: 'Ipsum Nisl'
    link: '#'
buttons:
  -
    text: 'Sign Up'
    link: '#'
